function R = rot_3D(phi)
    % clockwise rotation
    R = [  1           ,  0           ,  0           ; ...
           0           ,  cosd(phi(1)),  sind(phi(1)); ...
           0           , -sind(phi(1)),  cosd(phi(1))] * ...
        [  cosd(phi(3)),  sind(phi(3)),  0           ; ...
          -sind(phi(3)),  cosd(phi(3)),  0           ; ...
           0           ,  0           ,  1           ] * ...
        [  cosd(phi(2)),  0           , -sind(phi(2)); ...
           0           ,  1           ,  0           ; ...
           sind(phi(2)),  0           ,  cosd(phi(2))];
end